from .nodes import NODE_CLASS_MAPPINGS as BASE_NODE_CLASS_MAPPINGS
from .nodes import NODE_DISPLAY_NAME_MAPPINGS as BASE_NODE_DISPLAY_NAME_MAPPINGS
from .minimax_h3_prompt_nodes import NODE_CLASS_MAPPINGS as MINIMAX_H3_NODE_CLASS_MAPPINGS
from .minimax_h3_prompt_nodes import NODE_DISPLAY_NAME_MAPPINGS as MINIMAX_H3_NODE_DISPLAY_NAME_MAPPINGS


# 分开注册新旧节点，避免 MiniMax H3 功能影响工具箱中已经存在的节点。
NODE_CLASS_MAPPINGS = {
    **BASE_NODE_CLASS_MAPPINGS,
    **MINIMAX_H3_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **BASE_NODE_DISPLAY_NAME_MAPPINGS,
    **MINIMAX_H3_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
